# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57804d8514694d9b8dedd03508fdab764b396b1e1d928d3290ac7db721bd7e71d45c84159adb5a90062a8ee89ccd776bebc845f9d5ce7b9ce5dadcadfaa62b03

test:
  secret_key_base: 068a04691445ada19d3c434205b6da888afb9bab73592fe9d0d62ca24ae4203f8d330f7e7c5a5b782219f15614d747dcbb7dded0da5029d1b3b98732ea3d6715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
